language: python
python:
  - "3.7"
script:
- "./generate-tables.sh"
deploy:
- provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: 
    - master
notifications:
  email:
    on_success: change
    on_failure: always
