language: python
script:
- "./generate-tables.sh"
- "./deploy-to-gh-pages.sh"
env:
  global:
  - GITHUB_REPO: clarin-eric/resource-families-html-generator.git
  - secure: k47y1c4Ec02m7dcDVtWjOyIWmp1k67+PBf2XVyqF/ZbU+RYP23erb1dYTFsdhSJ3vtkllxQ9M6c7Si+eNELo+VGhpGI/ErejrAOsJlTFfhzst22XEVZjxX5q6CkTfI0qjjm3FZanQFoODJ4P1L6QXV9ahJQ917AKgT61QtEhPuDLjlWj0/SWbCDcBjB75JxkS3dZyei1yeAuOhZN/QGJVXQ85+L36qJAXgCdpKv60h+oW/hnvt9jpu+lbNpnVatXLW9UcYVOxXkNx+n3Dxk381cHRMdvp61AK7vxDfeRfALZwF1phKZg1z4r4Srrvi2DaP5M4sGCOyBdNNEACeLqVuaH+09AjKt4SOlLTGtI/7KeDZs22lL5mSn5CS5C3i5k5Edi0kJBAG9145pw+3sG8t8JCMEgC20gpG7D0+khBJI2fYtTAi3zS+uwQ6uPFPtzX3n3/sArOHyhPuDXOJ0IZeTIya+WDN+SsG1ruS2ikTcHSu9JlB7asQEKkHnqJFxQ+/gW+LGefNXIegNQokqT2hlAS3FD0F2pl+509tGszYnR0HTpsgCJpe0Wg6WnmsZNJCnCoNHQ+51KR5AQE9Jd+C8/TbuLqbimotdFb//AObrEYZvXrmKg6/SoUlmYTEjlDS9r2JXqRuuQgrqZLO+B7i1hOJERcq2Rn7zOYD04bUto=
