language: python
script:
- "./generate-tables.sh"
deploy:
- provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: 
    - dev
notifications:
  email:
    on_success: change
    on_failure: always
