name: Push Generated Clartables

on:
  [push]
defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update -y
          pip install .
      - name: Generate tables
        run: |
          mkdir tables || true
          ./rfhg/generate-tables.sh
      - name: Deploy tables to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4 # https://github.com/JamesIves/github-pages-deploy-action
        with:
          folder: ./tables/
